# Generated by Django 2.1.7 on 2020-03-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loged_in_detail',
            table='logedin_data',
        ),
    ]
