# Generated by Django 2.1.7 on 2020-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_user_app', '0002_auto_20200326_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loged_in_detail',
            name='mob_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
