# Generated by Django 2.1.7 on 2020-03-27 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_user_app', '0003_auto_20200327_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loged_in_detail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to=settings.AUTH_USER_MODEL),
        ),
    ]
