# Generated by Django 2.1.7 on 2020-03-27 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multi_user_app', '0004_auto_20200327_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_extra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
